### ISSUE TITLE
example paper not usable

### ISSUE THREAD

**Issue by chenwee** [meta-42/UnityFramework#2]
今天在找好的Unity开源库，想打开example看看效果是怎样的。但是看不到，画面一直只有
1，2，3，4 to change equipment 那句话

没有错误，按1，2，3，4也有打印，但是没画面
Unity 5.5  MACOS

麻烦看看是什么问题，还是本来就是这样的？

**Comment by meta-42** [comment]
1，2，3，4 to change equipment ？？？？  我的工程里应该没有这个啊？

**Comment by meta-42** [comment]
有没有截图，可以提给我看看吗？

**Comment by chenwee** [comment]
不好意思，我自己弄错了，打扰了
